services:
  db:
    image: "postgres:13-alpine"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=littledivelog
      - POSTGRES_DB=littledivelog
      - POSTGRES_PASSWORD=littledivelog
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./dev/pg/initdb.d:/docker-entrypoint-initdb.d

volumes:
  pg-data: 